import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Task } from 'src/app/Task';
import { ShipmentTypes } from 'src/app/shipmentTypes';
import { ProcurementTypes } from 'src/app/procurementTypes';
const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type': 'Application/json',
  }),
};

@Injectable({
  providedIn: 'root',
})
export class TaskService {
  private apiUrl = 'http://localhost:5000/tasks';
  constructor(private http: HttpClient) {}

  getTasks(): Observable<Task[]> {
    return this.http.get<Task[]>(this.apiUrl);
  }
  deleteTasks(task: Task): Observable<Task> {
    const url = `${this.apiUrl}/${task.id}`;
    return this.http.delete<Task>(url);
  }
  updateTaskReminder(task: Task): Observable<Task> {
    const url = `${this.apiUrl}/${task.id}`;
    return this.http.put<Task>(url, task, httpOptions);
  }
  addTask(task: Task): Observable<Task> {
    return this.http.post<Task>(this.apiUrl, task, httpOptions);
  }

  // shipmentTasks: ShipmentTypes[]
  entity() {
    return [
      {
        name: 'shipment',
        entity_id: 1
      },
      {
        name: 'procurement',
        entity_id:2,
      },
    ];
  }
  shipment() {
    return [
      {
        entity_id:1,
        name: 'Limbiq Reference ID',
        fieldName: 'limbiqReferenceId',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'externalId',
        name: 'External ID',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'status',
        name: 'Status',
        type: 'string',
        enumType: 'ShipmentStatus',
        valueMapping: {
          CARGO_PLANNED: 'Cargo Planned',
          CARGO_READY: 'Cargo Ready',
          SHIPMENT_PLACED: 'Shipment Placed',
          SHIPMENT_CONFIRMED: 'Shipment Confirmed',
          ESCALATION_CLARIFICATION: 'Clarification',
          CARGO_DISPATCHED: 'Cargo Dispatched',
          SHIPPED: 'Shipped',
          ARRIVED_AT_POD: 'Arrived at POD',
          SHIPPED_FROM_POD_TO_DESTINATION: 'Shipped from POD',
          ARRIVED_AT_DESTINATION: 'Arrived at Destination',
          CANCELLED: 'Cancelled',
        },
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=CONSIGNEE].groupPartner.groupName',
        name: 'Partner - Consignee - Company Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=CONSIGNEE].groupPartner.groupCode',
        name: 'Partner - Consignee - Company Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=CONSIGNEE].email',
        name: 'Partner - Consignee - Email',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=SHIPPER].groupPartner.groupName',
        name: 'Partner - Shipper - Company Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=SHIPPER].groupPartner.groupCode',
        name: 'Partner - Shipper - Company Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=SHIPPER].email',
        name: 'Partner - Shipper - Email',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=FORWARDER].groupPartner.groupName',
        name: 'Partner - Forwarder - Company Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=FORWARDER].groupPartner.groupCode',
        name: 'Partner - Forwarder - Company Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=FORWARDER].email',
        name: 'Partner - Forwarder - Email',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName:
          'extendedPartners[role=NOTIFICATION_PARTY].groupPartner.groupName',
        name: 'Partner - Notify Party - Company Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName:
          'extendedPartners[role=NOTIFICATION_PARTY].groupPartner.groupCode',
        name: 'Partner - Notify Party - Company Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedPartners[role=NOTIFICATION_PARTY].email',
        name: 'Partner - Notify Party - Email',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'carrier',
        name: 'Carrier',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'freightPaymentTerms',
        name: 'Freight Payment Terms',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'freightCostCurrency',
        name: 'Freight Cost Currency',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'vesselNumber.name',
        name: 'Vessel #/Flight #/Rail #/Truck',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'carrierReferenceNumber',
        name: 'Carrier Reference Number',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'onCarriage',
        name: 'On Carriage',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'shipmentType',
        name: 'Shipment Type',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.unNaNumber',
        name: 'Hazmat - UN/NA #',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.hazmatClass',
        name: 'Hazmat - Class',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.hazmatPackagingGroup',
        name: 'Hazmat - Packaging Grp',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.hazmatCommodity',
        name: 'Hazmat - Commodity',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.emergencyContact',
        name: 'Hazmat - Emergency Contact',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmatDetails.notes',
        name: 'Hazmat - Notes',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'newInstructions',
        name: 'Shipment Notes',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'mot',
        name: 'MOT',
        type: 'string',
        enumType: 'MOT',
        defaultValue: 'Sea',
        valueMapping: {
          AIR: 'Air',
          BARGE: 'Barge',
          BARGE_RAIL_TRUCK: 'Barge Rail Truck',
          BARGE_TRUCK: 'Barge Truck',
          NOT_APPLICABLE: 'Not Applicable',
          RAIL: 'Rail',
          RAIL_TRUCK: 'Rail truck',
          SEA: 'Sea',
          SEA_AIR: 'Sea Air',
          TRUCK: 'Truck',
        },
      },
      {
        entity_id:1,
        fieldName: 'incoterm',
        name: 'Incoterm',
        type: 'string',
        enumType: 'Incoterm',
        defaultValue: 'FOB',
        valueMapping: {
          CFR: 'CFR',
          CIF: 'CIF',
          CIP: 'CIP',
          CPT: 'CPT',
          DAP: 'DAP',
          DDP: 'DDP',
          DPU: 'DPU',
          EXW: 'EXW',
          FAS: 'FAS',
          FCA: 'FCA',
          FOB: 'FOB',
        },
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].address',
        name: 'Transshipport - Address',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].city.name',
        name: 'Transshipport - City - Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].city.unLocode',
        name: 'Transshipport - City - Unlocode',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].plannedTime',
        name: 'Transshipport - Planned Time',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].estimatedTime',
        name: 'Transshipport - Estimated Time',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].actualTime',
        name: 'Transshipport - Actual Time',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'measurementUnit',
        name: 'Quantity Type/UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'packagingType',
        name: 'Packaging Type',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionLength.uom',
        name: 'Pkg. Dim. Length UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionWidth.uom',
        name: 'Pkg. Dim. Width UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionHeight.uom',
        name: 'Pkg. Dim. Height UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.purchaseOrderLabel',
        name: 'Cargo Order #',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.productName',
        name: 'Cargo Product Name',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.productCode',
        name: 'Cargo Product Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.measurementUnit',
        name: 'Cargo Quantity Type/UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingType',
        name: 'Cargo Packaging Type',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionLength.uom',
        name: 'Cargo Pkg. Dim. Length UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionWidth.uom',
        name: 'Cargo Pkg. Dim. Width UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionHeight.uom',
        name: 'Cargo Pkg. Dim. Height UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.currency',
        name: 'Cargo Currency',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.unNaNumber',
        name: 'Cargo Hazmat - UN/NA #',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.hazmatClass',
        name: 'Cargo Hazmat - Class',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.hazmatPackagingGroup',
        name: 'Cargo Hazmat - Packaging Grp',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.hazmatCommodity',
        name: 'Cargo Hazmat - Commodity',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.emergencyContact',
        name: 'Cargo Hazmat - Emergency Contact',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmatDetails.notes',
        name: 'Cargo Hazmat - Notes',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.containerNumber',
        name: 'Cargo Container Number',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerNumber',
        name: 'CN Container Number',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerCode',
        name: 'CN Container Code',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerSize',
        name: 'CN Container Size',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerType',
        name: 'CN Container Type',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerCount',
        name: 'CN Container Count',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.containerCountMap',
        name: 'CN When container count used',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.measurementUnit',
        name: 'CN Quantity Type/UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingType',
        name: 'CN Packaging Type',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionLength.uom',
        name: 'CN Pkg. Dim. Length UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionWidth.uom',
        name: 'CN Pkg. Dim. Width UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionHeight.uom',
        name: 'CN Pkg. Dim. Height UOM',
        type: 'string',
      },
      {
        entity_id:1,
        fieldName: 'hazmat',
        name: 'Hazmat',
        type: 'boolean',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.hazmat',
        name: 'Cargo Hazmat',
        type: 'boolean',
      },
      {
        entity_id:1,
        fieldName: 'quantityValue',
        name: 'Quantity',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'grossWeight',
        name: 'Gross Weight/Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'netWeight',
        name: 'Net Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'volumeValue',
        name: 'Volume',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionLength.value',
        name: 'Pkg. Dim. Length',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionWidth.value',
        name: 'Pkg. Dim. Width',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'packagingDimensionHeight.value',
        name: 'Pkg. Dim. Height',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.quantityValue',
        name: 'Cargo Quantity',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.grossWeight',
        name: 'Cargo Gross Weight/Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.netWeight',
        name: 'Cargo Net Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.volumeValue',
        name: 'Cargo Volume',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionLength.value',
        name: 'Cargo Pkg. Dim. Length',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionWidth.value',
        name: 'Cargo Pkg. Dim. Width',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingDimensionHeight.value',
        name: 'Cargo Pkg. Dim. Height',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.unitPrice',
        name: 'Cargo Unit Price',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.quantityValue',
        name: 'CN Quantity',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.grossWeight',
        name: 'CN Gross Weight/Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.netWeight',
        name: 'CN Net Weight',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.volumeValue',
        name: 'CN Volume',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionLength.value',
        name: 'CN Pkg. Dim. Length',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionWidth.value',
        name: 'CN Pkg. Dim. Width',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingDimensionHeight.value',
        name: 'CN Pkg. Dim. Height',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'packagingQuantity',
        name: 'Packaging Quantity',
        type: 'integer',
      },
      {
        entity_id:1,
        fieldName: 'teu',
        name: 'TEU',
        type: 'integer',
      },
      {
        entity_id:1,
        fieldName: 'extendedCargos.packagingQuantity',
        name: 'Cargo Packaging Quantity',
        type: 'integer',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.packagingQuantity',
        name: 'CN Packaging Quantity',
        type: 'integer',
      },
      {
        entity_id:1,
        fieldName: 'extendedContainers.teu',
        name: 'CN TEU',
        type: 'integer',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].plannedDate',
        name: 'Transshipport - Planned Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].estimatedDate',
        name: 'Transshipport - Estimated Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'extendedTransshipPorts[type=POL].actualDate',
        name: 'Transshipport - Actual Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'crdValue',
        name: 'CRD',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'freightCost',
        name: 'Freight Cost',
        type: 'double',
      },
      {
        entity_id:1,
        fieldName: 'cyCutoff',
        name: 'CY Cutoff',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'docCutoff',
        name: 'Doc Cutoff',
        type: 'ZonedDateTime',
      },
      {
        entity_id:1,
        fieldName: 'additionalReferences[referencename=?].referencefieldName',
        name: 'Additional Reference',
        type: 'any',
      },
    ];
  }
  //procurementTasks: ProcurementTypes[]
  procurement() {
    return [
      {
        entity_id:2,
        fieldName: 'purchaseOrderLabel',
        name: 'Order #',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'status',
        name: 'Status',
        type: 'string',
        enumType: 'ProcurementStatus',
        valueMapping: {
          SUBMITTED: 'Submitted',
          REQUEST_CHANGES: 'Requested Changes',
          APPROVE_CHANGES: 'Approved Changes',
          REJECT_CHANGES: 'Rejected Changes',
          REJECTED: 'Rejected',
          CANCELLED: 'Cancelled',
          PO_CONFIRMED: 'Order Confirmed',
          CARGO_PLANNED: 'Cargo Planned',
          CARGO_READY: 'Cargo Ready',
          SHIPMENT_PLACED: 'Shipment Placed',
          SHIPMENT_CONFIRMED: 'Shipment Confirmed',
          ESCALATION_CLARIFICATION: 'Clarification',
          CARGO_DISPATCHED: 'Cargo Dispatched',
          SHIPPED: 'Shipped',
          ARRIVED_AT_POD: 'Arrived at POD',
          SHIPPED_FROM_POD_TO_DESTINATION: 'Shipped from POD',
          ARRIVED_AT_DESTINATION: 'Arrived at Destination',
        },
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=CONSIGNEE].groupPartner.groupName',
        name: 'Partner - Consignee - Company Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=CONSIGNEE].groupPartner.groupCode',
        name: 'Partner - Consignee - Company Code',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=CONSIGNEE].email',
        name: 'Partner - Consignee - Email',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=SHIPPER].groupPartner.groupName',
        name: 'Partner - Shipper - Company Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=SHIPPER].groupPartner.groupCode',
        name: 'Partner - Shipper - Company Code',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=SHIPPER].email',
        name: 'Partner - Shipper - Email',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=FORWARDER].groupPartner.groupName',
        name: 'Partner - Forwarder - Company Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=FORWARDER].groupPartner.groupCode',
        name: 'Partner - Forwarder - Company Code',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=FORWARDER].email',
        name: 'Partner - Forwarder - Email',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName:
          'extendedPartners[role=NOTIFICATION_PARTY].groupPartner.groupName',
        name: 'Partner - Notify Party - Company Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName:
          'extendedPartners[role=NOTIFICATION_PARTY].groupPartner.groupCode',
        name: 'Partner - Notify Party - Company Code',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedPartners[role=NOTIFICATION_PARTY].email',
        name: 'Partner - Notify Party - Email',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'newInstructions',
        name: 'Order Notes',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'mot',
        name: 'MOT',
        type: 'string',
        enumType: 'MOT',
        defaultValue: 'Sea',
        valueMapping: {
          AIR: 'Air',
          BARGE: 'Barge',
          BARGE_RAIL_TRUCK: 'Barge Rail Truck',
          BARGE_TRUCK: 'Barge Truck',
          NOT_APPLICABLE: 'Not Applicable',
          RAIL: 'Rail',
          RAIL_TRUCK: 'Rail truck',
          SEA: 'Sea',
          SEA_AIR: 'Sea Air',
          TRUCK: 'Truck',
        },
      },
      {
        entity_id:2,
        fieldName: 'incoterm',
        name: 'Incoterm',
        type: 'string',
        enumType: 'Incoterm',
        defaultValue: 'FOB',
        valueMapping: {
          CFR: 'CFR',
          CIF: 'CIF',
          CIP: 'CIP',
          CPT: 'CPT',
          DAP: 'DAP',
          DDP: 'DDP',
          DPU: 'DPU',
          EXW: 'EXW',
          FAS: 'FAS',
          FCA: 'FCA',
          FOB: 'FOB',
        },
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].address',
        name: 'Transshipport - Address',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].city.name',
        name: 'Transshipport - City - Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].city.unLocode',
        name: 'Transshipport - City - Unlocode',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].plannedTime',
        name: 'Transshipport - Planned Time',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].estimatedTime',
        name: 'Transshipport - Estimated Time',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].actualTime',
        name: 'Transshipport - Actual Time',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'measurementUnit',
        name: 'Quantity Type/UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'packagingType',
        name: 'Packaging Type',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionLength.uom',
        name: 'Pkg. Dim. Length UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionWidth.uom',
        name: 'Pkg. Dim. Width UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionHeight.uom',
        name: 'Pkg. Dim. Height UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'confirmationNumber',
        name: 'Order Confirmation #',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.productName',
        name: 'PO Product Name',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.measurementUnit',
        name: 'PO Quantity Type/UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingType',
        name: 'PO Packaging Type',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionLength.uom',
        name: 'PO Pkg. Dim. Length UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionWidth.uom',
        name: 'PO Pkg. Dim. Width UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionHeight.uom',
        name: 'PO Pkg. Dim. Height UOM',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.currency',
        name: 'PO Currency',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.unNaNumber',
        name: 'PO Hazmat - UN/NA #',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.hazmatClass',
        name: 'PO Hazmat - Class',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.hazmatPackagingGroup',
        name: 'PO Hazmat - Packaging Grp',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.hazmatCommodity',
        name: 'PO Hazmat - Commodity',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.emergencyContact',
        name: 'PO Hazmat - Emergency Contact',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmatDetails.notes',
        name: 'PO Hazmat - Notes',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.newInstructions',
        name: 'PO Product - Notes',
        type: 'string',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.hazmat',
        name: 'PO Hazmat',
        type: 'boolean',
      },
      {
        entity_id:2,
        fieldName: 'quantityValue',
        name: 'Quantity',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'grossWeight',
        name: 'Gross Weight/Weight',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'netWeight',
        name: 'Net Weight',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'volumeValue',
        name: 'Volume',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionLength.value',
        name: 'Pkg. Dim. Length',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionWidth.value',
        name: 'Pkg. Dim. Width',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'packagingDimensionHeight.value',
        name: 'Pkg. Dim. Height',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.quantityValue',
        name: 'PO Quantity',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.grossWeight',
        name: 'PO Gross Weight/Weight',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.netWeight',
        name: 'PO Net Weight',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.volumeValue',
        name: 'PO Volume',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionLength.value',
        name: 'PO Pkg. Dim. Length',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionWidth.value',
        name: 'PO Pkg. Dim. Width',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingDimensionHeight.value',
        name: 'PO Pkg. Dim. Height',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.unitPrice',
        name: 'PO Unit Price',
        type: 'double',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.packagingQuantity',
        name: 'PO Packaging Quantity',
        type: 'integer',
      },
      {
        entity_id:2,
        fieldName: 'packagingQuantity',
        name: 'Packaging Quantity',
        type: 'integer',
      },
      {
        entity_id:2,
        fieldName: 'teu',
        name: 'TEU',
        type: 'integer',
      },
      {
        entity_id:2,
        fieldName: 'orderPlacedDate',
        name: 'Order Placed Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].plannedDate',
        name: 'Transshipport - Planned Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].estimatedDate',
        name: 'Transshipport - Estimated Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'extendedTransshipPorts[type=POL].actualDate',
        name: 'Transshipport - Actual Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'orderPlacedDate',
        name: 'Order Placed Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'confirmedDate',
        name: 'Order Confirmed Date',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'extendedDeliveries.crdValue',
        name: ' PO CRD',
        type: 'ZonedDateTime',
      },
      {
        entity_id:2,
        fieldName: 'additionalReferences[referencename=?].referencefieldName',
        name: 'Additional Reference',
        type: 'any',
      },
    ];
  }
}
